# Generated by Django 5.2 on 2025-04-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_inf', '0002_mensagemcontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tecnologias', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='MensagemContato',
        ),
    ]
