# Generated by Django 5.2 on 2025-05-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_inf', '0003_projeto_delete_curso_delete_mensagemcontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('curso', models.CharField(choices=[('SI', 'Sistemas de Informação'), ('CC', 'Ciência da Computação')], max_length=2)),
                ('ano_conclusao', models.PositiveIntegerField()),
            ],
        ),
    ]
