# Generated by Django 5.2.1 on 2025-05-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_inf', '0005_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('site', models.URLField(blank=True)),
                ('descricao', models.TextField(blank=True)),
                ('contato', models.EmailField(blank=True, max_length=254)),
                ('destaque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('local', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('Estágio', 'Estágio'), ('Emprego', 'Emprego'), ('Trainee', 'Trainee'), ('Outro', 'Outro')], max_length=50)),
                ('link', models.URLField(blank=True)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('data_expiracao', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='site_inf.empresaparceira')),
            ],
        ),
    ]
