# Generated by Django 5.1.7 on 2025-05-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_inf', '0006_empresaparceira_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='exaluno',
            name='cidade',
            field=models.CharField(default='Santa Maria', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exaluno',
            name='latitude',
            field=models.FloatField(default=-29.6842),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exaluno',
            name='longitude',
            field=models.FloatField(default=-53.8069),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresaparceira',
            name='contato',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
