# Generated by Django 5.1.7 on 2025-05-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_inf', '0007_exaluno_cidade_exaluno_latitude_exaluno_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exaluno',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='exaluno',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='exaluno',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='curso',
            field=models.CharField(choices=[('SI', 'Sistemas de Informação'), ('CC', 'Ciência da Computação')], max_length=2),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
