# Generated by Django 5.1.7 on 2025-05-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_inf', '0008_tcc_remove_exaluno_cidade_remove_exaluno_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcc',
            name='autor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcc',
            name='palavras_chave',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
