# Generated by Django 5.1.7 on 2025-05-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_inf', '0009_tcc_autor_tcc_palavras_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='exaluno',
            name='cidade_atual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exaluno',
            name='empresa_atual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exaluno',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exaluno',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exaluno',
            name='pais_atual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
