# Generated by Django 5.2.1 on 2025-06-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_inf', '0010_exaluno_cidade_atual_exaluno_empresa_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcc',
            name='arquivo_tcc',
            field=models.FileField(blank=True, null=True, upload_to='tccs/'),
        ),
    ]
