# Generated by Django 5.2.1 on 2025-06-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_inf', '0011_tcc_arquivo_tcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='categoria',
            field=models.CharField(choices=[('ENSINO', 'Ensino'), ('EXTENSAO', 'Extensão'), ('PESQUISA', 'Pesquisa')], default='PESQUISA', max_length=20, verbose_name='Categoria do Projeto'),
        ),
    ]
