# Generated by Django 5.2.1 on 2025-06-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_inf', '0012_projeto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título da Publicação')),
                ('autores', models.TextField(help_text='Liste os autores. Ex: Silva, J.; Souza, A.; Pereira, L.')),
                ('evento_ou_revista', models.CharField(max_length=500, verbose_name='Nome do Evento, Revista ou Livro')),
                ('ano', models.IntegerField(verbose_name='Ano de Publicação')),
                ('link_pdf', models.URLField(blank=True, null=True, verbose_name='Link para o PDF')),
                ('link_bibtex', models.URLField(blank=True, null=True, verbose_name='Link para o BibTeX')),
                ('link_doi', models.URLField(blank=True, null=True, verbose_name='Link para DOI (Digital Object Identifier)')),
                ('link_outro', models.URLField(blank=True, null=True, verbose_name='Outro Link (Ex: App, Código, Apresentação)')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-ano', 'titulo'],
            },
        ),
    ]
