# Generated by Django 5.1.7 on 2025-06-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_inf', '0013_publicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exaluno',
            name='cidade_atual',
        ),
        migrations.RemoveField(
            model_name='exaluno',
            name='pais_atual',
        ),
        migrations.AddField(
            model_name='exaluno',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo',
            field=models.CharField(choices=[('Estágio', 'Estágio'), ('Emprego', 'Emprego'), ('Iniciação Científica', 'Iniciação Científica'), ('Outro', 'Outro')], max_length=50),
        ),
    ]
