# Generated by Django 5.1.7 on 2025-07-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_inf', '0014_remove_exaluno_cidade_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcc',
            name='pdf_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
